stages:
  download:
    cmd: python source/download.py
    params:
    - params/params.yaml:
      - download.n_locs
      - download.year
      - download.seed
    outs:
    - data/
  prepare:
    cmd: python source/prepare.py
    deps:
    - data/
    outs:
    - outputs/prepare_output.csv
    - outputs/daily_fields_list.txt
  process:
    cmd: python source/process.py
    deps:
    - data/
    - outputs/daily_fields_list.txt
    outs:
    - outputs/process_output.csv
  evaluate:
    cmd: python source/evaluate.py
    deps:
    - outputs/process_output.csv
    - outputs/prepare_output.csv
    outs:
    - outputs/evaluate_output.csv
